[package]
name = "fendermint_eth_api"
description = "Ethereum JSON-RPC facade"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
ethers-core = { workspace = true }
axum = { workspace = true }
jsonrpc-v2 = { workspace = true, features = ["easy-errors"] }
paste = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tendermint = { workspace = true }
tendermint-rpc = { workspace = true }

fvm_shared = { workspace = true }

fendermint_rpc = { path = "../../rpc" }
fendermint_vm_actor_interface = { path = "../../vm/actor_interface" }
fendermint_vm_core = { path = "../../vm/core" }
fendermint_vm_genesis = { path = "../../vm/genesis" }

[dev-dependencies]
clap = { workspace = true }
ethers = { workspace = true, features = ["abigen"] }
hex = { workspace = true }
lazy_static = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
