# smoke-test infrastructure:
# cargo install cargo-make
#
# cd fendermint/testing/smoke-test
# - then -
# cargo make --profile ci
# - or -
# cargo make setup
# cargo make test
# docker logs smoke-ethapi
# cargo make teardown

extend = [
  { path = "../Makefile/common.toml" },
]

env_files = [
  { path = "./snapshot.env" },
  { path = "../Makefile/common.env" },
  { path = "../Makefile/ci.env", profile = "ci" },
]

[tasks.test]
clear = true
dependencies = ["snapshot-test"]


[tasks.snapshot-test]
script = """
echo "Hello Snapshots!"
"""

# Overriding th env file to enable snapshotting.
[tasks.test-data-env]
script = """
cat << EOF > ${TEST_DATA_DIR}/.env
FM_DB__HIST_SIZE=100
FM_SNAPSHOTS__ENABLED=true
FM_SNAPSHOTS__BLOCK_INTERVAL=10
FM_SNAPSHOTS__HIST_SIZE=10
FM_SNAPSHOTS__CHUNK_SIZE_BYTES=1048576
FM_SNAPSHOTS__SYNC_POLL_INTERVAL=10
EOF
"""
