[env]
CHAIN_NAME = { value = "root", condition = { env_not_set = ["CHAIN_NAME"] }}
BALANCE = { value = "1000", condition = { env_not_set = ["BALANCE"] }}
BASE_FEE = { value = "1000", condition = { env_not_set = ["BASE_FEE"] }}
TIMESTAMP = { value = "1680101412", condition = { env_not_set = ["TIMESTAMP"] }}

BASE_DIR="${HOME}"
FM_DIR="${BASE_DIR}/.fendermint/${CHAIN_NAME}"
CMT_DIR="${BASE_DIR}/.cometbft/${CHAIN_NAME}"

GENESIS_FILE="${FM_DIR}/genesis.json"
KEYS_DIR="${FM_DIR}/keys"
KEY_NAME="validator_key"
PUB_KEY_PATH="${KEYS_DIR}/${KEY_NAME}.pk"
PRIV_KEY_PATH="${KEYS_DIR}/${KEY_NAME}.sk"

NETWORK_NAME = "${CHAIN_NAME}-network"
CMT_CONTAINER_NAME = "${CHAIN_NAME}-cometbft"
FM_CONTAINER_NAME = "${CHAIN_NAME}-fendermint"
ETHAPI_CONTAINER_NAME = "${CHAIN_NAME}-ethapi"

CMT_DOCKER_IMAGE = "cometbft/cometbft:v0.37.x"
FM_DOCKER_IMAGE = "fendermint:latest"
TEST_DATA_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/fendermint/testing/smoke-test/test-data"
TEST_SCRIPTS_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/fendermint/testing/smoke-test/scripts"
ACTORS_BUNDLE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/../builtin-actors/output/bundle.car"
CMT_HOST_PORT = 26657
ETHAPI_HOST_PORT = 8545
# If this wasn't present, any wait task is skipped.
CARGO_MAKE_WAIT_MILLISECONDS = 5000
# This wait time seems to work locally.
CMT_WAIT_MILLIS = 10000
# Keep example logs to a minimum.
VERBOSITY = ""

[env.ci]
CMT_WAIT_MILLIS = 20000
# Help debug any issues with simplecoin by logging requests and responses.
VERBOSITY = "--verbose"

# infrastructure workflows:
# cargo install cargo-make
#
# cd fendermint/testing/smoke-test
# - then -
# cargo make --profile ci
# - or -
# cargo make setup
# cargo make test
# docker logs smoke-ethapi
# cargo make teardown

[tasks.info]
script="""
echo
echo Chain:
echo - Chain: ${CHAIN_NAME}
echo - Balance: ${BALANCE}
echo - Base Fee: ${BASE_FEE}
echo - Timestamp: ${TIMESTAMP}
echo
echo Directories and files:
echo - Home directory: ${BASE_DIR}
echo - Keys directory: ${KEYS_DIR}
echo - Genesis file: ${GENESIS_FILE}
echo - CometBFT directory: ${CMT_DIR}
echo - Fendermint directory: ${FM_DIR}
echo - Private key: ${PRIV_KEY_PATH}
echo
echo Docker:
echo - Network: ${NETWORK_NAME}
echo - CometBFT container: ${CMT_CONTAINER_NAME}
echo - Fendermint container: ${FM_CONTAINER_NAME}
echo
"""

[tasks.init]
dependencies = [
  "clear",
  "createbasedir",
  "newgenesis",
  "newkey",
  "newaccount",
  "newgateway"
]

[tasks.clear]
script="""
echo clearing all data in: $FM_DIR $CMT_DIR
rm -rf ${FM_DIR}
rm -rf ${CMT_DIR}
"""

[tasks.createbasedir]
script="""
echo creating directories: $FM_DIR $CMT_DIR
mkdir -p $FM_DIR

mkdir -p $CMT_DIR
mkdir -p $CMT_DIR/data
mkdir -p $CMT_DIR/config
"""

[tasks.newkey]
cwd = "./target/release"
script="""
mkdir -p $KEYS_DIR
./fendermint key gen --out-dir $KEYS_DIR --name $KEY_NAME;
chmod 600 ${PRIV_KEY_PATH}
"""

[tasks.newaccount]
cwd = "./target/release"
script="""
./fendermint genesis --genesis-file ${GENESIS_FILE} add-account --public-key ${PUB_KEY_PATH} --balance ${BALANCE}
"""

[tasks.newgenesis]
cwd = "./target/release"
script = """
./fendermint genesis --genesis-file ${GENESIS_FILE} new --chain-name ${CHAIN_NAME} --base-fee ${BASE_FEE} --timestamp ${TIMESTAMP}
"""
dependencies = [
  "createbasedir",
]

[tasks.newgateway]
cwd = "./target/release"
script = """
./fendermint genesis --genesis-file ${GENESIS_FILE} add-validator --public-key ${PUB_KEY_PATH} --power 1

./fendermint genesis --genesis-file ${GENESIS_FILE} ipc gateway --subnet-id /r0 \
    --top-down-check-period 10 \
    --bottom-up-check-period 10 \
    --msg-fee 10 \
    --majority-percentage 66

./fendermint genesis --genesis-file ${GENESIS_FILE} into-tendermint --out ${CMT_DIR}/config/genesis.json

./fendermint key into-tendermint --secret-key ${PRIV_KEY_PATH} --out ${CMT_DIR}/data/priv_validator_key.json

chmod 600 ${CMT_DIR}/data/priv_validator_key.json
"""

[tasks.default]
clear = true
script_runner = "@duckscript"
script = ['''
    echo
    echo Main tasks:
    echo - clear: Clear all information: private keys, cache, database, etc.
    echo - init: Initialize the system
    echo - info: Print the setup information
    echo - start: Starts Fendermint/CometBFT docker containers with the genesis
    echo - teardown: Stops the system and clears all data
    echo - run: Inits and then starts the system
    echo
    echo Most tasks use these environment variables:
    echo - CHAIN_NAME (default '${CHAIN_NAME}'): the target IPC subnet
    echo
    echo Run 'cargo make -e CHAIN_NAME=chain -e BALANCE=100 -e BASE_FEE=200 ... COMMAND' to populate the variables from CLI or
    echo Run 'cargo make --env-file=/PATH/.env COMMAND' to populate the variables from the file before running the command.
    echo
    echo Run 'cargo make --list-all-steps' for a complete list of available tasks.
    echo
''']


# Waiting before starting the Eth API for the CometBFT websocket to start listening.
[tasks.start]
dependencies = [
  "network-create",
  "cometbft-init",
  "fendermint-deps",
  "fendermint-start",
  "cometbft-start",
]

[tasks.run]
dependencies = [
  "init",
  "start",
]

[tasks.setupold]
dependencies = [
  "test-data-dir",
  "network-create",
  "cometbft-init",
  "fendermint-deps",
  "fendermint-init",
  "fendermint-start",
  "cometbft-start",
  "cometbft-wait",
  "ethapi-start",
  "fendermint-logs",
  "cometbft-logs",
  "ethapi-logs",
]

[tasks.test]
clear = true
dependencies = ["simplecoin-example", "ethapi-example"]

[tasks.teardown]
# `dependencies` doesn't seem to work with `cleanup_task`.
run_task = { name = [
  "cometbft-stop",
  "cometbft-rm",
  "fendermint-stop",
  "fendermint-rm",
  "ethapi-stop",
  "ethapi-rm",
  "network-rm",
  "clear",
] }


[tasks.simplecoin-example]
# Using --release in the hope that it can reuse artifacts compiled earlier for the docker build.
script = """
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cargo run -p fendermint_rpc --release --example simplecoin -- \
  --secret-key fendermint/testing/smoke-test/test-data/fendermint/keys/alice.sk \
  ${VERBOSITY}
"""


[tasks.ethapi-example]
script = """
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cargo run -p fendermint_eth_api --release --example ethers -- \
  --secret-key-from fendermint/testing/smoke-test/test-data/fendermint/keys/emily.sk \
  --secret-key-to   fendermint/testing/smoke-test/test-data/fendermint/keys/eric.sk
"""


[tasks.test-data-dir-rm]
script = """
rm -rf ${TEST_DATA_DIR}
"""


[tasks.cometbft-pull]
command = "docker"
args = ["pull", "${CMT_DOCKER_IMAGE}"]

[tasks.cometbft-init]
extend = "cometbft-run"
env = { "CMD" = "init", "FLAGS" = "-a STDOUT -a STDERR --rm" }

[tasks.cometbft-start]
extend = "cometbft-run"
env = { "CMD" = "start", "FLAGS" = "-d" }

[tasks.cometbft-wait]
extend = "wait"
env = { "CARGO_MAKE_WAIT_MILLISECONDS" = "${CMT_WAIT_MILLIS}" }

[tasks.cometbft-run]
script = """
docker run \
  ${FLAGS} \
  --name ${CMT_CONTAINER_NAME} \
  --user $(id -u) \
  --network ${NETWORK_NAME} \
  --publish 26657:${CMT_HOST_PORT} \
  --volume ${CMT_DIR}:/cometbft \
  --env CMT_PROXY_APP=tcp://${FM_CONTAINER_NAME}:26658 \
  --env CMT_PEX=false \
  ${CMT_DOCKER_IMAGE} \
  ${CMD}
"""
dependencies = ["cometbft-pull", "createbasedir", "network-create"]

[tasks.cometbft-rm]
extend = "docker-rm"
env = { "CONTAINER_NAME" = "${CMT_CONTAINER_NAME}" }

[tasks.cometbft-stop]
extend = "docker-stop"
env = { "CONTAINER_NAME" = "${CMT_CONTAINER_NAME}" }

[tasks.cometbft-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${CMT_CONTAINER_NAME}" }

[tasks.fendermint-deps]
script = """
# Check if the image exists
# TODO: Check the version or use a flag to always re-build?
if docker images | awk '{print $1":"$2}' | grep fendermint; then
    echo fendermint image already exists
    docker images | grep fendermint
else
    cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
    make docker-build
fi
"""

[tasks.fendermint-init]
extend = "fendermint-run"
env = { "ENTRY" = "/scripts/init.sh", "FLAGS" = "-a STDOUT -a STDERR --rm" }

[tasks.fendermint-start]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "run", "FLAGS" = "-d" }

[tasks.fendermint-run]
script = """
docker run \
  ${FLAGS} \
  --name ${FM_CONTAINER_NAME} \
  --init \
  --user $(id -u) \
  --network ${NETWORK_NAME} \
  --volume ${FM_DIR}/data:/data \
  --env FM_DATA_DIR=/data/fendermint/data \
  --env FM_CHAIN_NAME=${NETWORK_NAME} \
  --env LOG_LEVEL=info \
  --entrypoint ${ENTRY} \
  ${FM_DOCKER_IMAGE} \
  ${CMD}
"""
dependencies = ["createbasedir", "network-create", "fendermint-deps"]

[tasks.ethapi-start]
extend = "ethapi-run"
env = { "CMD" = "eth run", "FLAGS" = "-d" }


[tasks.ethapi-run]
script = """
docker run \
  ${FLAGS} \
  --name ${ETHAPI_CONTAINER_NAME} \
  --init \
  --user $(id -u) \
  --network ${NETWORK_NAME} \
  --publish 8545:${ETHAPI_HOST_PORT} \
  --env TENDERMINT_WS_URL=ws://${CMT_CONTAINER_NAME}:26657/websocket \
  --env LOG_LEVEL=debug \
  --env RUST_BACKTRACE=1 \
  ${FM_DOCKER_IMAGE} \
  ${CMD}
"""
dependencies = ["network-create"]

[tasks.network-create]
command = "docker"
args = ["network", "create", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.network-rm]
command = "docker"
args = ["network", "rm", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.fendermint-rm]
extend = "docker-rm"
env = { "CONTAINER_NAME" = "${FM_CONTAINER_NAME}" }

[tasks.fendermint-stop]
extend = "docker-stop"
env = { "CONTAINER_NAME" = "${FM_CONTAINER_NAME}" }

[tasks.ethapi-rm]
extend = "docker-rm"
env = { "CONTAINER_NAME" = "${ETHAPI_CONTAINER_NAME}" }

[tasks.ethapi-stop]
extend = "docker-stop"
env = { "CONTAINER_NAME" = "${ETHAPI_CONTAINER_NAME}" }

[tasks.ethapi-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${ETHAPI_CONTAINER_NAME}" }

[tasks.fendermint-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${FM_CONTAINER_NAME}" }

[tasks.docker-stop]
command = "docker"
args = ["stop", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-rm]
command = "docker"
args = ["rm", "--force", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-logs]
command = "docker"
args = ["logs", "${CONTAINER_NAME}"]
ignore_errors = true
