[workspace]
members = ["fendermint/abci", "fendermint/app", "fendermint/rocksdb", "fendermint/storage", "fendermint/testing", "fendermint/vm/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license = "MIT OR Apache-2.0"
license-file = "LICENSE-APACHE"


[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
async-stm = "0.2"
arbitrary = { version = "1", features = ["derive"] }
arbtest = "0.2"
futures = "0.3"
paste = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_tuple = "0.5"
tokio = { version = "1", features = ["rt-multi-thread"] }
tempfile = "3.3"
thiserror = "1"
quickcheck = "1"
quickcheck_macros = "1"
libsecp256k1 = "0.7"
rand = "0.8"
rand_chacha = "0.3"
hex = "0.4"
base64 = "0.21"
num-traits = "0.2"


# Stable FVM dependencies from crates.io
fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.3"
fvm_ipld_car = "0.6"
# Using 0.8 because of ref-fvm.
# 0.9 would be better because of its updated quickcheck dependency.
# 0.10 breaks some API.
cid = { version = "0.8", features = ["serde-codec", "std"] }

# The following are on crates.io but they might be pre-releases.
fvm = { version = "3.1", default-features = false }     # no opencl feature or it fails on CI
fvm_shared = { version = "3.1", features = ["crypto"] }

# Tendermint dependencies are forked because we are building against 0.37 release candidates.
tower-abci = { git = "https://github.com/consensus-shipyard/tower-abci.git", branch = "tendermint-v0.37" }
tendermint = { git = "https://github.com/aakoshh/tendermint-rs.git", branch = "mikhail/multi-tc-version-support" }
