[workspace]
members = ["fendermint/abci", "fendermint/app", "fendermint/storage", "fendermint/testing", "fendermint/vm/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license = "MIT OR Apache-2.0"
license-file = "LICENSE-APACHE"


[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
async-stm = "0.1.2"
futures = "0.3"
paste = "1"
serde = { version = "1", features = ["derive"] }
serde_tuple = "0.5"
tokio = { version = "1", features = ["rt-multi-thread"] }
tempfile = "3.3"
thiserror = "1"
quickcheck = "1"
quickcheck_macros = "1"

# Stable FVM dependencies from crates.io
cid = { version = "0.8", default-features = false, features = ["serde-codec", "std", "arb"] }
fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.3"
fvm_ipld_car = "0.6"

# The following are on crates.io but as pre-releases.
fvm = { version = "3.0.0-alpha.22", default-features = false } # no opencl or it fails on CI
fvm_shared = "3.0.0-alpha.18"

# Tendermint dependencies are forked because we are building against 0.37 release candidates.
tower-abci = { git = "https://github.com/consensus-shipyard/tower-abci.git", branch = "tendermint-v0.37" }
tendermint = { git = "https://github.com/aakoshh/tendermint-rs.git", branch = "mikhail/multi-tc-version-support" }
