[workspace]
members = ["fendermint/abci", "fendermint/app", "fendermint/vm/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license = "MIT OR Apache-2.0"
license-file = "LICENSE-APACHE"


[workspace.dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
tempfile = "3.3"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_tuple = "0.5"
cid = { version = "0.8", default-features = false, features = ["serde-codec", "std", "arb"] }

# Stable FVM dependencies from crates.io
fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.3"
fvm_ipld_car = "0.6"

# The following are on crates.io but as pre-releases.
fvm = { version = "3.0.0-alpha.21", default-features = false } # no opencl or it fails on CI
fvm_shared = "3.0.0-alpha.17"
