[package]
name = "fendermint_vm_core"
description = "Core data structures shared between genesis and messages"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
