# Data directory relative to the `--home-dir`, unless given as an absolute path.
data_dir = "data"
# Contract directory relative to the `--home-dir`, unless given as an absolute path.
contracts_dir = "contracts"
# Builtin actor bundle path relative to the `--home-dir`, unless given as an absolute path.
builtin_actors_bundle = "bundle.car"

[abci]
bound = 1

[abci.listen]
# Only accept connections from Tendermint, assumed to be running locally.
host = "127.0.0.1"
# The default port where Tendermint is going to connect to the application.
port = 26658

[db]
# Keep unlimited history by default.
state_hist_size = 0

# Ethereum API facade
[eth]
# Maximum time allowed between polls for filter changes, in seconds, before the subscription is canceled.
filter_timeout = 300

[eth.listen]
# Only accept local connections by default.
host = "127.0.0.1"
# The default port where the Ethereum API will listen to
# JSON-RPC (POST) and WebSockets (GET) requests.
port = 8545
