# All directories can be either:
# * an absolute path, starting with "/", e.g. "/foo/bar"
# * a path relative to the system `$HOME` directory, starting with "~", e.g. "~/foo/bar"
# * a path relative to the `--home-dir` directory passed to the CLI, e.g. "foo/bar"

# Database files.
data_dir = "data"
# Private key.
keys_dir = "keys"
# Solidity contracts.
contracts_dir = "contracts"
# Builtin actor bundle CAR file.
builtin_actors_bundle = "bundle.car"

[abci]
# Number of concurrent requests allowed to reach the application.
bound = 1

[abci.listen]
# Only accept connections from Tendermint, assumed to be running locally.
host = "127.0.0.1"
# The default port where Tendermint is going to connect to the application.
port = 26658

[db]
# Keep unlimited history by default.
state_hist_size = 0

# FVM configuration
[fvm]
# Overestimation rate applied to gas estimations to ensure that the
# message goes through
gas_overestimation_rate = 1.25
# Gas search step increase used to find the optimal gas limit.
# It determines how fine-grained we want the gas estimation to be.
gas_search_step = 1.25
# Indicate whether transactions should be fully executed during the checks performed
# when they are added to the mempool, or just the most basic ones are performed.
#
# Enabling this option is required to fully support "pending" queries in the Ethereum API,
# otherwise only the nonces and balances are projected into a partial state.
exec_in_check = true

# Ethereum API facade
[eth]
# Maximum time allowed between polls for filter changes, in seconds, before the subscription is canceled.
filter_timeout = 300
# Maximum number of entries in the LRU caches.
cache_capacity = 1000000

[eth.gas]
# Minimum gas premium returned by the API in `eth_maxPriorityFeePerGas`
min_gas_premium = 100000
# Number of blocks used for the computation of the premium in `eth_maxPriorityFeePerGas`
# Default: Lotus uses only 2 epochs to compupte the premium, but they compute the
# median over (on average) 10 blocks, 5 per epoch.
num_blocks_max_prio_fee = 10
# Maximum size of the histogram for `eth_feeHistory`
max_fee_hist_size = 1024

[eth.listen]
# Only accept local connections by default.
host = "127.0.0.1"
# The default port where the Ethereum API will listen to
# JSON-RPC (POST) and WebSockets (GET) requests.
port = 8545
