name: Install Tools
description: "Install platform dependencies and tools"
inputs:
  repo-token:
    description: "secrets.GITHUB_TOKEN"
    required: true

runs:
  using: "composite"

  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: wasm32-unknown-unknown
        toolchain: ${{ matrix.rust }}
        components: rustfmt,clippy

    - name: Install Cargo Make
      uses: davidB/rust-cargo-make@v1

    # Protobuf compiler required by libp2p-core
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.repo-token }}

    # For compiling Solidity contracts
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
