# smoke-test infrastructure:
# cargo install cargo-make
#
# cd fendermint/testing/smoke-test
# - then -
# cargo make --profile ci
# - or -
# cargo make setup
# cargo make test
# docker logs smoke-ethapi
# cargo make teardown

extend = [
  { path = "../Makefile/common.toml" },
]

env_files = [
  { path = "./smoke.env" },
  { path = "../Makefile/common.env" },
  { path = "../Makefile/ci.env", profile = "ci" },
]

[tasks.test]
clear = true
dependencies = ["simplecoin-example", "ethapi-example"]


[tasks.simplecoin-example]
# Using --release in the hope that it can reuse artifacts compiled earlier for the docker build.
script = """
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cargo run -p fendermint_rpc --release --example simplecoin -- \
  --secret-key fendermint/testing/smoke-test/test-data/keys/alice.sk \
  ${VERBOSITY}
"""


[tasks.ethapi-example]
script = """
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cargo run -p fendermint_eth_api --release --example ethers -- \
  --secret-key-from fendermint/testing/smoke-test/test-data/keys/emily.sk \
  --secret-key-to   fendermint/testing/smoke-test/test-data/keys/eric.sk
"""
