[package]
name = "fendermint_vm_interpreter"
description = "Execute messages using the FVM"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fendermint_vm_actor_interface = { path = "../actor_interface" }
fendermint_vm_core = { path = "../core" }
fendermint_vm_genesis = { path = "../genesis" }
fendermint_vm_message = { path = "../message" }

async-trait = { workspace = true }
anyhow = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

cid = { workspace = true }
fvm = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_car = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
tokio = { workspace = true }

fendermint_vm_genesis = { path = "../genesis", features = ["arb"] }

[features]
default = []
bundle = []
