[package]
name = "fendermint_vm_interpreter"
description = "Execute messages using the FVM"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fendermint_vm_actor_interface = { path = "../actor_interface" }
ipc_actors_abis = { git = "https://github.com/consensus-shipyard/ipc-solidity-actors.git", branch = "dev" }
fendermint_vm_core = { path = "../core" }
fendermint_vm_genesis = { path = "../genesis" }
fendermint_vm_message = { path = "../message" }
fendermint_vm_resolver = { path = "../resolver" }
fendermint_eth_hardhat = { path = "../../eth/hardhat" }

async-trait = { workspace = true }
async-stm = { workspace = true }
anyhow = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
libsecp256k1 = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tendermint = { workspace = true }
tendermint-rpc = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

cid = { workspace = true }
fvm = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_car = { workspace = true }

futures-core = "0.3.28"
futures-util = "0.3.28"
libipld = { version = "0.14", default-features = false, features = ["dag-cbor"] }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
pin-project = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
fvm = { workspace = true, features = ["arb", "testing"] }
fendermint_vm_genesis = { path = "../genesis", features = ["arb"] }
tempfile = "3.7.0"

[features]
default = []
bundle = []
