[package]
name = "fendermint_vm_snapshot"
description = "Produce and consume ledger snapshots"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-stm = { workspace = true }
cid = { workspace = true }
futures = { workspace = true }
multihash = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

tendermint = { workspace = true }
tendermint-rpc = { workspace = true }

fvm_ipld_blockstore = { workspace = true }
fvm_ipld_car = { workspace = true }
fvm_ipld_encoding = { workspace = true }

fendermint_vm_interpreter = { path = "../interpreter" }

[dev-dependencies]
fendermint_vm_interpreter = { path = "../interpreter", features = ["bundle"] }
