[tasks.docker-network-create]
command = "docker"
args = ["network", "create", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.docker-network-rm]
command = "docker"
args = ["network", "rm", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.docker-stop]
command = "docker"
args = ["stop", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-rm]
command = "docker"
args = ["rm", "--force", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-logs]
command = "docker"
args = ["logs", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-id]
command = "docker"
args = ["exec", "${CONTAINER_NAME}", "cometbft show-node-id"]
ignore_errors = true
