########################################################################################################################
# Node helpers
########################################################################################################################

[tasks.node-down]
dependencies = [
    "cometbft-stop",
    "cometbft-rm"
]

[tasks.new-node]
dependencies = [
    "node-down",
    "bootstrap-mkdir",
    "docker-network-create",
    "cometbft-config",
    "seed-enable",
    "fendermint-deps",
    "subnet-config",
    "fendermint-start",
    "cometbft-start",
    "cometbft-wait",
    "cometbft-node-id",
    "node-report",
]

[tasks.node-init]
dependencies = [
    "node-clear",
    "node-mkdir",
]

[tasks.node-clear]
script="""
echo clearing all IPC data
rm -rf ${BASE_DIR}
"""

[tasks.bootstrap-mkdir]
script="""
echo creating directories: $BASE_DIR $CMT_DIR
mkdir -p $BASE_DIR
mkdir -p $CMT_DIR
"""

[tasks.node-mkdir]
script="""
echo creating directories: $BASE_DIR $FM_DIR $CMT_DIR
mkdir -p $BASE_DIR

mkdir -p $FM_DIR
mkdir -p $CMT_DIR
"""