########################################################################################################################
# Node helpers
########################################################################################################################

[tasks.node-down]
dependencies = [
    "cometbft-stop",
    "cometbft-rm"
]

[tasks.new-node]
dependencies = [
    "node-down",
    "bootstrap-mkdir",
    "cometbft-bootstrap-init",
    "seed-enable",
    "set-seeds",
    "cometbft-bootstrap-start",
    "cometbft-wait",
    "cometbft-node-id",
]

[tasks.node-init]
dependencies = [
    "node-clear",
    "node-mkdir",
]

[tasks.node-clear]
script="""
echo clearing all IPC data
rm -rf ${BASE_DIR}
"""

[tasks.bootstrap-mkdir]
script="""
echo creating directories: $BASE_DIR $CMT_DIR
mkdir -p $BASE_DIR
mkdir -p $CMT_DIR
"""

[tasks.node-mkdir]
script="""
echo creating directories: $BASE_DIR $FM_DIR $CMT_DIR
mkdir -p $BASE_DIR

mkdir -p $FM_DIR
mkdir -p $CMT_DIR
"""

[tasks.seed-enable]
script="""
sed -i'' -e "s|seed_mode = false|seed_mode = true|" ${CMT_DIR}/config/config.toml
"""

[tasks.addr-book-enable]
script="""
sed -i'' -e "s|addr_book_strict = false|addr_book_strict = true|" ${CMT_DIR}/config/config.toml
"""

[tasks.set-seeds]
script = """
sed -i'' -e 's|^seeds = ""$|seeds = "{{PLACEHOLDER}}"|g' ${CMT_DIR}/config/config.toml
sed -i "s/{{PLACEHOLDER}}/$BOOTSTRAPS/g" ${CMT_DIR}/config/config.toml
"""

[tasks.set-external-addr]
script = """
sed -i'' -e 's|^external_address = ""$|external_address = "{{PLACEHOLDER}}"|g' ${CMT_DIR}/config/config.toml
sed -i "s/{{PLACEHOLDER}}/$COMETBFT_EXTERNAL_ADDR/g" ${CMT_DIR}/config/config.toml
"""

[tasks.cometbft-config]
dependencies = [
    "seed-enable",
    "addr-book-enable",
    "set-external-addr",
]