########################################################################################################################
# Node helpers
########################################################################################################################
[tasks.node-down]
dependencies = [
    "cometbft-stop",
    "cometbft-rm"
]

[tasks.new-node]
dependencies = [
    "node-down",
    "node-init",
    "cometbft-init",
    "seed-enable",
    "cometbft-start"
]

[tasks.node-init]
dependencies = [
    "node-clear",
    "node-mkdir",
]

[tasks.node-clear]
script="""
echo clearing all IPC data
rm -rf ${BASE_DIR}
"""

[tasks.node-mkdir]
script="""
echo creating directories: $BASE_DIR $FM_DIR $CMT_DIR
mkdir -p $BASE_DIR
mkdir -p $FM_DIR

mkdir -p $CMT_DIR
"""

[tasks.seed-enable]
script="""
sed -i'bak' "s/seed_mode = false/seed_mode = true/" ${BASE_DIR}/cometbft/config/config.toml
"""