########################################################################################################################
# Testnode
########################################################################################################################
[tasks.testnode]
workspace = false
dependencies = [
    "testnode-down",
    "testnode-init",
    "testnode-network-create",
    "cometbft-init",
    "fendermint-deps",
    "testnode-config",
    "fendermint-start",
    "cometbft-start",
    "cometbft-wait",
    "ethapi-start",
    "testnode-report",
]

[tasks.testnode-network-create]
env = { "NETWORK_NAME"="${NETWORK_NAME}"}
extend = "docker-network-create"

[tasks.testnode-init]
dependencies = [
    "node-clear",
    "node-mkdir",
]

[tasks.testnode-clear]
script="""
echo clearing all IPC data
rm -rf ${BASE_DIR}
"""

[tasks.testnode-mkdir]
script="""
echo creating directories: $BASE_DIR $FM_DIR $CMT_DIR
mkdir -p $BASE_DIR
mkdir -p $FM_DIR

mkdir -p $CMT_DIR
"""

[tasks.testnode-down]
# `dependencies` doesn't seem to work with `cleanup_task`.
run_task = { name = [
    "cometbft-stop",
    "cometbft-rm",
    "fendermint-stop",
    "fendermint-rm",
    "ethapi-stop",
    "ethapi-rm",
    "docker-network-rm"
]}

# This task create all necessary data structures to run Fendermint:
# the genesis file with necessary entities and cryptographic keys.
[tasks.testnode-config]
dependencies = [
    "testnode-new-genesis",
    "testnode-new-key",
    "testnode-new-accounts",
    "testnode-add-validator",
    "testnode-new-gateway",
    "testnode-write-genesis",
    "testnode-export-keys"
]

[tasks.testnode-new-genesis]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "genesis --genesis-file /data/genesis.json new --chain-name ${CHAIN_NAME} --base-fee ${BASE_FEE} --timestamp ${TIMESTAMP} --power-scale 3" }

[tasks.testnode-new-key]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "key gen --out-dir /data/${KEYS_SUBDIR} --name ${KEY_NAME}" }
script.pre = "mkdir -p ${BASE_DIR}/${KEYS_SUBDIR}"
script.post = "chmod 600 ${BASE_DIR}/${PRIV_KEY_PATH}"

[tasks.testnode-new-accounts]
dependencies = ["testnode-new-account-f1", "testnode-new-account-eth"]

[tasks.testnode-new-account-f1]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "genesis --genesis-file /data/genesis.json add-account --public-key /data/${PUB_KEY_PATH} --balance ${BALANCE}" }

[tasks.testnode-new-account-eth]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "genesis --genesis-file /data/genesis.json add-account --kind ethereum --public-key /data/${PUB_KEY_PATH} --balance ${BALANCE}" }

[tasks.testnode-add-validator]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "genesis --genesis-file /data/genesis.json add-validator --public-key /data/${PUB_KEY_PATH} --power 1" }

[tasks.testnode-new-gateway]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = """genesis --genesis-file /data/genesis.json ipc gateway --subnet-id /r0 \
    --bottom-up-check-period 10 \
    --msg-fee 10 \
    --majority-percentage 67 \
    --min-collateral 1""" }

[tasks.testnode-write-genesis]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "genesis --genesis-file /data/genesis.json into-tendermint --out /data/genesis.committed.json" }
script.post = "cp ${BASE_DIR}/genesis.committed.json ${CMT_DIR}/config/genesis.json"

[tasks.testnode-export-keys]
extend = "fendermint-run"
env = { "ENTRY" = "fendermint", "CMD" = "key into-tendermint --secret-key /data/${PRIV_KEY_PATH} --out /data/priv_validator_key.json" }
script.post = "cp ${BASE_DIR}/priv_validator_key.json ${CMT_DIR}/config/priv_validator_key.json; chmod 600 ${CMT_DIR}/config/priv_validator_key.json"

[tasks.testnode-report]
script = """cat << EOF
############################
#                          #
# Testnode ready! 🚀       #
#                          #
############################

Eth API:
\thttp://0.0.0.0:8545

Accounts:
$(jq -r '.accounts[] | "\t\\(.meta.Account.owner): \\(.balance) coin units"' ${BASE_DIR}/genesis.json)

Private key (hex ready to import in MetaMask):
\t$(cat ${BASE_DIR}/${PRIV_KEY_PATH} | base64 -d | xxd -p -c 1000000)

Note: both accounts use the same private key @ ${BASE_DIR}/${PRIV_KEY_PATH}

Chain ID:
\t$(curl -s --location --request POST 'http://localhost:8545/' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc":"2.0", "method":"eth_chainId", "params":[], "id":1 }' | jq -r '.result' | xargs printf "%d")

Fendermint API:
\thttp://localhost:26658

CometBFT API:
\thttp://0.0.0.0:26657
EOF
"""