########################################################################################################################
# Testnet
########################################################################################################################
[tasks.testnet]
dependencies = [
    "testnet-down",
    "testnet-init",
    "fendermint-deps",
    "testnet-up"
]

[tasks.testnet-up]
script = """
if [ -z $GID ]; then GID=$(id -g); fi
if [ -z $UID ]; then UID=$(id -u); fi
export UID
export GID
export CMT_PERSISTENT_PEERS=`cat $BASE_DIR/peers`
export SUBNET_ID=$SUBNET_ID
export BASE_DIR=$BASE_DIR
./infra/run.sh start
"""

[tasks.testnet-down]
dependencies = [
    "testnet-docker-compose-down",
    "docker-network-rm",
]

[tasks.testnet-docker-compose-down]
script = """
export CMT_PERSISTENT_PEERS="UNDEFINED"
if [ -z $GID ]; then GID=$(id -g); fi
if [ -z $UID ]; then UID=$(id -u); fi
export UID
export GID
./infra/run.sh stop
"""

[tasks.testnet-init]
dependencies = [
    "testnet-clear",
    "docker-network-create",
    "cometbft-pull",
    "testnet-mkdir",
    "genesis-new",
    "testnet-init-nodes",
    "genesis-write",
    "testnet-copy-genesis",
    "testnet-setup-persistent-peers",
]

[tasks.testnet-init-nodes]
script_runner = "@duckscript"
script = """
nodes = range 0 4

for i in ${nodes}
    NUMBER = set ${i}
    NODE_DIR = set "node${NUMBER}"
    KEYS_SUBDIR = set "${NODE_DIR}/keys"
    KEY_NAME = set "validator${NUMBER}"

    mkdir -p ${BASE_DIR}/${NODE_DIR}
    mkdir -p ${BASE_DIR}/${NODE_DIR}/fendermint
    mkdir -p ${BASE_DIR}/${NODE_DIR}/cometbft

    set_env NODE_DIR ${NODE_DIR}
    set_env NUMBER ${NUMBER}

    cm_run_task testnet-node-cometbft-init

    set_env KEYS_SUBDIR ${KEYS_SUBDIR}
    set_env KEY_NAME ${KEY_NAME}

    cm_run_task genesis-new-key

    set_env PUB_KEY_PATH "${KEYS_SUBDIR}/${KEY_NAME}.pk"
    set_env PRIV_KEY_PATH "${KEYS_SUBDIR}/${KEY_NAME}.sk"

    cm_run_task genesis-new-accounts
    cm_run_task genesis-add-validator

    set_env COMETBFT_SUBDIR ${NODE_DIR}/cometbft

    cm_run_task testnet-add-peer
    cm_run_task testnode-export-keys
end

release ${nodes}
"""

[tasks.testnet-clear]
script="""
echo clearing all IPC data
rm -rf ${BASE_DIR}
"""

[tasks.testnet-mkdir]
script="""
mkdir -p $BASE_DIR
mkdir -p $BASE_DIR/out
"""

[tasks.testnet-node-cometbft-init]
extend = "cometbft-init"
env = { "CMD" = "init", "NETWORK_NAME"="${NETWORK_NAME}", "CMT_DIR" = "${BASE_DIR}/${NODE_DIR}/cometbft", "CMT_CONTAINER_NAME" = "cometbft-node0", "FLAGS" = "-a STDOUT -a STDERR --rm"}

[tasks.testnet-add-peer]
extend = "fendermint-tool"
env = { "ENTRY" = "fendermint", "CMD" = """key add-peer \
        --node-key-file /data/${COMETBFT_SUBDIR}/config/node_key.json \
        --network-addr 192.167.10.$((${NUMBER}+2)):26656 \
        --local-peers-file /data/peers \
""" }

<<<<<<< HEAD
[tasks.testnet-setup-persistent-peers]
=======
[tasks.testnet-cometbft-init-node2]
extend = "cometbft-init"
env = { "CMD" = "init", "NETWORK_NAME"="${NETWORK_NAME}", "CMT_DIR" = "${BASE_DIR}/node2/cometbft", "CMT_CONTAINER_NAME" = "cometbft-node2", "FLAGS" = "-a STDOUT -a STDERR --rm"  }

[tasks.testnet-cometbft-init-node3]
extend = "cometbft-init"
env = { "CMD" = "init", "NETWORK_NAME"="${NETWORK_NAME}", "CMT_DIR" = "${BASE_DIR}/node3/cometbft", "CMT_CONTAINER_NAME" = "cometbft-node3", "FLAGS" = "-a STDOUT -a STDERR --rm"  }

[tasks.testnet-config]
dependencies = [
    "testnet-script-new-genesis",
    "testnet-script-add-peers",
    "testnet-script-new-key",
    "testnet-script-new-account",
    "testnet-script-new-gateway",
    "testnet-script-share-genesis"
]

[tasks.testnet-script-new-genesis]
cwd = "./target/release"
script = """
./fendermint genesis --genesis-file $BASE_DIR/genesis.json \
      new --chain-name ${SUBNET_ID} --base-fee ${BASE_FEE} --timestamp ${TIMESTAMP} --power-scale ${POWER_SCALE}

cat $BASE_DIR/genesis.json
"""

[tasks.testnet-script-new-key]
cwd = "./target/release"
>>>>>>> main
script="""
unset CMT_PERSISTENT_PEERS
export CMT_PERSISTENT_PEERS=`cat $BASE_DIR/peers`
echo Persistent peers: $CMT_PERSISTENT_PEERS

for i in $(seq 0 3); do
    sed -i'bak' "s/persistent_peers = \\"\\"/persistent_peers = \\"$CMT_PERSISTENT_PEERS\\"/" $BASE_DIR/node${i}/cometbft/config/config.toml
done
"""

[tasks.testnet-copy-genesis]
script = """
for i in $(seq 0 3); do
    cp $BASE_DIR/genesis.committed.json $BASE_DIR/node${i}/cometbft/config/genesis.json
done
"""
