version: '3'

services:
  node0:
    container_name: node0
    image: "cometbft/localnode"
    environment:
      - ID=0
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./genesis.json:/cometbft/config/genesis.json
      - ./abci0/validator.json:/cometbft/config/priv_validator_key.json
    command: node --proxy_app=tcp://abci0:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "cometbft/localnode"
    environment:
      - ID=1
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./genesis.json:/cometbft/config/genesis.json
      - ./abci1/validator.json:/cometbft/config/priv_validator_key.json
    command: node --proxy_app=tcp://abci1:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    image: "cometbft/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./genesis.json:/cometbft/config/genesis.json
      - ./abci2/validator.json:/cometbft/config/priv_validator_key.json
    command: node --proxy_app=tcp://abci2:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    image: "cometbft/localnode"
    environment:
      - ID=3
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./genesis.json:/cometbft/config/genesis.json
      - ./abci3/validator.json:/cometbft/config/priv_validator_key.json
    command: node --proxy_app=tcp://abci3:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  abci0:
    container_name: abci0
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - NETWORK_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - NODE_ID=abci0
      - BASE_DIR=/root/fendermint
      - UID=0
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node0:26657
      - TENDERMINT_RPC_URL=http://node0:26657
      - FM_VALIDATOR_KEY__PATH=/root/fendermint/data/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - FM_NETWORK=test
      - RUST_BACKTRACE=1
    volumes:
      - ./localnet/abci0/private_key:/root/fendermint/data/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - NETWORK_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - NODE_ID=abci1
      - BASE_DIR=/root/fendermint
      - UID=0
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node1:26657
      - TENDERMINT_RPC_URL=http://node1:26657
      - FM_VALIDATOR_KEY__PATH=/root/fendermint/data/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./localnet/abci1/private_key:/root/fendermint/data/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    container_name: abci2
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - NETWORK_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - NODE_ID=abci2
      - BASE_DIR=/root/fendermint
      - UID=0
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node2:26657
      - TENDERMINT_RPC_URL=http://node2:26657
      - FM_VALIDATOR_KEY__PATH=/root/fendermint/data/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./localnet/abci2/private_key:/root/fendermint/data/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    container_name: abci3
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - NETWORK_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - NODE_ID=abci3
      - BASE_DIR=/root/fendermint
      - UID=0
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node3:26657
      - TENDERMINT_RPC_URL=http://node3:26657
      - FM_VALIDATOR_KEY__PATH=/root/fendermint/data/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./localnet/abci3/private_key:/root/fendermint/data/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16