version: '3'

services:
  node0:
    container_name: node0
    image: "cometbft/localnode"
    ports:
      - 26657:26657
    environment:
      - ID=0
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./cometbft:/cometbft/cometbft
      - ./abci0/node_key.json:/cometbft/node0/config/node_key.json
      - ./abci0/genesis.json:/cometbft/node0/config/genesis.json
      - ./abci0/validator.json:/cometbft/node0/config/priv_validator_key.json
      - ./abci0/data:/cometbft/node0/data:Z
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://abci0:26658 --p2p.persistent_peers="784acc66e95ccdcd354e11468a40e84e0e88cba4@192.167.10.2:26656,51da5a20a302529200387f2afbdaaba2b1263734@192.167.10.3:26656,ce0f1b6bf95a5cd8a6be767b284773a32e5c5bd4@192.167.10.4:26656,ea1b191d1629c8fa1e12d5e0a6139e75883740d3@192.167.10.5:26656"
    networks:
      localnet:
        ipv4_address: 192.167.10.2
    depends_on:
     - abci0

  node1:
    container_name: node1
    image: "cometbft/localnode"
    environment:
      - ID=1
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./cometbft:/cometbft/cometbft
      - ./abci1/node_key.json:/cometbft/node1/config/node_key.json
      - ./abci1/genesis.json:/cometbft/node1/config/genesis.json
      - ./abci1/validator.json:/cometbft/node1/config/priv_validator_key.json
      - ./abci1/data:/cometbft/node1/data:Z
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://abci1:26658 --p2p.persistent_peers="784acc66e95ccdcd354e11468a40e84e0e88cba4@192.167.10.2:26656,51da5a20a302529200387f2afbdaaba2b1263734@192.167.10.3:26656,ce0f1b6bf95a5cd8a6be767b284773a32e5c5bd4@192.167.10.4:26656,ea1b191d1629c8fa1e12d5e0a6139e75883740d3@192.167.10.5:26656"
    networks:
      localnet:
        ipv4_address: 192.167.10.3
    depends_on:
      - abci1

  node2:
    container_name: node2
    image: "cometbft/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./cometbft:/cometbft/cometbft
      - ./abci2/node_key.json:/cometbft/node2/config/node_key.json
      - ./abci2/genesis.json:/cometbft/node2/config/genesis.json
      - ./abci2/validator.json:/cometbft/node2/config/priv_validator_key.json
      - ./abci2/data:/cometbft/node2/data:Z
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://abci2:26658 --p2p.persistent_peers="784acc66e95ccdcd354e11468a40e84e0e88cba4@192.167.10.2:26656,51da5a20a302529200387f2afbdaaba2b1263734@192.167.10.3:26656,ce0f1b6bf95a5cd8a6be767b284773a32e5c5bd4@192.167.10.4:26656,ea1b191d1629c8fa1e12d5e0a6139e75883740d3@192.167.10.5:26656"
    networks:
      localnet:
        ipv4_address: 192.167.10.4
    depends_on:
      - abci2

  node3:
    container_name: node3
    image: "cometbft/localnode"
    environment:
      - ID=3
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./cometbft:/cometbft/cometbft
      - ./abci3/node_key.json:/cometbft/node3/config/node_key.json
      - ./abci3/genesis.json:/cometbft/node3/config/genesis.json
      - ./abci3/validator.json:/cometbft/node3/config/priv_validator_key.json
      - ./abci3/data:/cometbft/node3/data:Z
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://abci3:26658 --p2p.persistent_peers="784acc66e95ccdcd354e11468a40e84e0e88cba4@192.167.10.2:26656,51da5a20a302529200387f2afbdaaba2b1263734@192.167.10.3:26656,ce0f1b6bf95a5cd8a6be767b284773a32e5c5bd4@192.167.10.4:26656,ea1b191d1629c8fa1e12d5e0a6139e75883740d3@192.167.10.5:26656"
    networks:
      localnet:
        ipv4_address: 192.167.10.5
    depends_on:
      - abci3

  abci0:
    container_name: abci0
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node0:26657
      - TENDERMINT_RPC_URL=http://node0:26657
      - FM_VALIDATOR_KEY__PATH=/fendermint/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - FM_NETWORK=test
      - RUST_BACKTRACE=1
    volumes:
      - ./abci0/abci0.sk:/fendermint/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node1:26657
      - TENDERMINT_RPC_URL=http://node1:26657
      - FM_VALIDATOR_KEY__PATH=/fendermint/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./abci1/abci1.sk:/fendermint/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    container_name: abci2
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node2:26657
      - TENDERMINT_RPC_URL=http://node2:26657
      - FM_VALIDATOR_KEY__PATH=/fendermint/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./abci2/abci2.sk:/fendermint/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    container_name: abci3
    image: "fendermint:latest"
    entrypoint: "fendermint"
    command: "run"
    environment:
      - FM_DATA_DIR=/root/fendermint/data
      - FM_LOG_DIR=/root/fendermint/data/logs
      - FM_CHAIN_NAME=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__SUBNET_ID=/r314159/t410f6c5hpqeqau4idqe7mund4tilojxdihutnmk7enq
      - FM_IPC__TOPDOWN__CHAIN_HEAD_DELAY=10
      - FM_IPC__TOPDOWN__PARENT_HTTP_ENDPOINT=https://api.calibration.node.glif.io/rpc/v1
      - FM_IPC__TOPDOWN__PARENT_REGISTRY=0x5FE1a06cA4534cB878260522a572e2254214261D
      - FM_IPC__TOPDOWN__PARENT_GATEWAY=0x2e994B75095a39EB7C6dDA0516731B02AbcDbdb4
      - FM_IPC__TOPDOWN__EXPONENTIAL_BACK_OFF=5
      - FM_IPC__TOPDOWN__EXPONENTIAL_RETRY_LIMIT=5
      - FM_IPC__TOPDOWN__POLLING_INTERVAL=10
      - FM_IPC__TOPDOWN__PROPOSAL_DELAY=2
      - FM_IPC__TOPDOWN__MAX_PROPOSAL_RANGE=100
      - FM_ABCI__LISTEN__HOST=0.0.0.0
      - FM_ETH__LISTEN__HOST=0.0.0.0
      - FM_TENDERMINT_RPC_URL=http://node3:26657
      - TENDERMINT_RPC_URL=http://node3:26657
      - FM_VALIDATOR_KEY__PATH=/fendermint/private_key
      - FM_VALIDATOR_KEY__KIND=ethereum
      - LOG_LEVEL=info
      - RUST_BACKTRACE=1
      - FM_NETWORK=test
    volumes:
      - ./abci3/abci3.sk:/fendermint/private_key
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16