[package]
name = "fendermint_app"
description = "Tendermint ABCI++ Application to implement an IPLD+FVM enabled sidechain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
tendermint = { workspace = true }

fendermint_abci = { path = "../abci" }
fendermint_vm_interpreter = { path = "../vm/interpreter" }
fendermint_vm_message = { path = "../vm/message" }

cid = { workspace = true }
fvm = { workspace = true }
fvm_ipld_car = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_shared = { workspace = true }

# The current 0.2.0 version of forest_db is not published to crates.io.
# Using the `tag` of the `forest` repo rather than the `version` of just `forest_db` so we don't get a random commit in `main`.
forest_db = { git = "https://github.com/ChainSafe/forest.git", tag = "v0.6.0", features = ["rocksdb"] }

[dev-dependencies]
tempfile = { workspace = true }

# Load the same built-in actor bundle as the ref-fvm integration tests. We'll probably need built-in actors,
# for example to deploy Solidity code. We can compile Wasm actors and deploy them too, but certain functions
# in `ref-fvm` like looking up actor addresses depend on built-in actors like the `InitActor` maintaining state.
# TODO: This is dev-dependency for testing - in prod it whould be taken from a file, not packaged with the app, so the release cycle is independent.
# TODO: Figure out how to load only what we need, and nothing else.
actors-v10 = { package = "fil_builtin_actors_bundle", git = "https://github.com/filecoin-project/builtin-actors", branch = "next", features = ["m2-native"] }
