[package]
name = "fendermint_vm_actor_interface"
description = "Re-export interfaces of built-in actors, either copyed versions or from direct project reference."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fvm_shared = { workspace = true }
