[package]
name = "fendermint_vm_actor_interface"
description = "Re-export interfaces of built-in actors, either copyed versions or from direct project reference."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }

cid = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
frc42_dispatch = { workspace = true }

fendermint_vm_genesis = { path = "../genesis" }
