[package]
name = "fendermint_vm_message"
description = "Messages (transactions) received on chain and passed on to the FVM"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_encoding = { workspace = true }
